---
# Sample inventory for Stargate
# Usage: ansible-inventory -i inventory/stargate.ini --list

[stargate]
localhost ansible_connection=local ansible_python_interpreter=auto_silent

[stargate:vars]
stargate_server=https://pms.tony.lab.ctc-g.com.my:9443
stargate_username=admin
stargate_password=password
stargate_validate_certs=false