---
# defaults file for login role

stargate_server: "https://YOUR_SERVER_IP:8443"
stargate_username: ""
stargate_password: ""
stargate_validate_certs: false
stargate_use_ssl: true
stargate_timeout: 30

stargate_token_raw: ""
stargate_logged_in: false