---
# defaults file for account role

stargate_server: "https://YOUR_SERVER_IP:8443"
stargate_token: ""
stargate_validate_certs: false
stargate_use_ssl: true
stargate_timeout: 30

account_operation: get
account_start: 0
account_length: 10
account_data: {}

accounts: []
created_account: {}
account_password: {}